package nl.cofano.schedulerapp.scheduler;

import java.time.Instant;

/**
 * The Entity for storing all the schedulers
 * The getters & setters are generated by lombok (https://projectlombok.org/)
 */
public class ScheduleItem {
    private Integer id;

    private String cronExpression;
    private Instant lastExecuted;

    private String description;
    private Integer assignee;

    @java.beans.ConstructorProperties({"id", "cronExpression", "lastExecuted", "description", "assignee"})
    public ScheduleItem(Integer id, String cronExpression, Instant lastExecuted, String description, Integer assignee) {
        this.id = id;
        this.cronExpression = cronExpression;
        this.lastExecuted = lastExecuted;
        this.description = description;
        this.assignee = assignee;
    }

    public ScheduleItem() {
    }

    public Integer getId() {
        return this.id;
    }

    public String getCronExpression() {
        return this.cronExpression;
    }

    public Instant getLastExecuted() {
        return this.lastExecuted;
    }

    public String getDescription() {
        return this.description;
    }

    public Integer getAssignee() {
        return this.assignee;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    public void setLastExecuted(Instant lastExecuted) {
        this.lastExecuted = lastExecuted;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setAssignee(Integer assignee) {
        this.assignee = assignee;
    }
}
